package by.tc.task05.controller.command;

import jakarta.servlet.annotation.WebInitParam;

public enum CommandName {
    GOTOSIGNIN, GOTOREGISTRATION, SAVENEWUSER, GOTOSEARCHPAGE, SIGNIN, SIGNOUT,
    CHANGELANGUAGE, GOTOSTARTERPAGE, ACCOUNT, GOTOEDITUSERINFOPAGE,
    EDITUSERINFO, GOTOEDITEMAILPAGE, EDITEMAIL, GOTOEDITPASSWORDPAGE,
    EDITPASSWORD, GOTODELETEACCOUNTPAGE, DELETEACCOUNT, GOTOSETAVATARPAGE,
    SETAVATAR, GOTOADDHOTELPAGE, ADDHOTEL, GOTOHOTELMANAGEMENTPAGE,
    GOTOSETHOTELICONPAGE, SETHOTELICON, GOTODELETEHOTELPAGE, DELETEHOTEL,
    GOTOCHANGEHOTELPAGE, CHANGEHOTEL, GOTOADMINSPAGE, GOTOADDADMINPAGE,
    ADDADMIN, GOTODELETEADMINPAGE, DELETEADMIN, GOTOHOTELPAGE, GOTOADDROOMPAGE,
    ADDROOM, GOTOCHANGEROOMPAGE, CHANGEROOM, GOTODELETEROOMPAGE, DELETEROOM,
    GOTOSETROOMICONPAGE, SETROOMICON, GOTOROOMPAGE;
}
