package by.tc.task05.controller.command;

public enum CommandName {
	GOTOSIGNIN, GOTOREGISTRATION, SAVENEWUSER,
	GOTOSEARCHPAGE, SIGNIN, SIGNOUT,CHANGELANGUAGE, GOTOSTARTERPAGE, ACCOUNT,
	GOTOEDITUSERINFOPAGE, EDITUSERINFO
}
